// examples/vue3/src/App.vue
<script setup>
import {
  Dashboard,
  DashboardModal,
  DragDrop,
  ProgressBar,
} from "@growthcloud/vue";
</script>

<template>
  <div id="app">
    <!-- <HelloWorld msg="Welcome to Uppy Vue Demo"/> -->
    <h1>Welcome to Uppy Vue Demo!</h1>
    <h2>Inline Dashboard</h2>
    <label>
      <input
        type="checkbox"
        :checked="showInlineDashboard"
        @change="
          (event) => {
            showInlineDashboard = event.target.checked;
          }
        "
      />
      Show Dashboard
    </label>
    <Dashboard
      v-if="showInlineDashboard"
      :uppy="uppy"
      :props="{
        metaFields: [{ id: 'name', name: 'Name', placeholder: 'File name' }],
      }"
    />
    <h2>Modal Dashboard</h2>
    <div>
      <button @click="open = true">Show Dashboard</button>
      <DashboardModal
        :uppy="uppy2"
        :open="open"
        :props="{
          onRequestCloseModal: handleClose,
        }"
      />
    </div>

    <h2>Drag Drop Area</h2>
    <DragDrop
      :uppy="uppy"
      :props="{
        locale: {
          strings: {
            chooseFile: 'Boop a file',
            orDragDrop: 'or yoink it here',
          },
        },
      }"
    />

    <h2>Progress Bar</h2>
    <ProgressBar
      :uppy="uppy"
      :props="{
        hideAfterFinish: false,
      }"
    />
  </div>
</template>

<script>
import Uppy from "@growthcloud/core";
import Tus from "@growthcloud/tus";
import { defineComponent } from "vue";

const { VITE_TUS_ENDPOINT: TUS_ENDPOINT } = import.meta.env;

export default defineComponent({
  computed: {
    uppy: () =>
      new Uppy({ id: "uppy1", autoProceed: true, debug: true }).use(Tus, {
        endpoint: TUS_ENDPOINT,
      }),
    uppy2: () =>
      new Uppy({ id: "uppy2", autoProceed: false, debug: true }).use(Tus, {
        endpoint: TUS_ENDPOINT,
      }),
  },
  data() {
    return {
      open: false,
      showInlineDashboard: false,
    };
  },
  methods: {
    handleClose() {
      this.open = false;
    },
  },
});
</script>

<style src="@growthcloud/core/dist/style.css"></style>
<style src="@growthcloud/dashboard/dist/style.css"></style>
<style src="@growthcloud/drag-drop/dist/style.css"></style>
<style src="@growthcloud/progress-bar/dist/style.css"></style>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// examples/react-example/App.jsx
/* eslint-disable */
import React from "react";
import Uppy from "@growthcloud/core";
import Tus from "@growthcloud/tus";
import GoogleDrive from "@growthcloud/google-drive";
import {
  Dashboard,
  DashboardModal,
  DragDrop,
  ProgressBar,
  FileInput,
} from "@growthcloud/react";

import "@growthcloud/core/dist/style.css";
import "@growthcloud/dashboard/dist/style.css";
import "@growthcloud/drag-drop/dist/style.css";
import "@growthcloud/file-input/dist/style.css";
import "@growthcloud/progress-bar/dist/style.css";

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      showInlineDashboard: false,
      open: false,
    };

    this.uppy = new Uppy({ id: "uppy1", autoProceed: true, debug: true })
      .use(Tus, { endpoint: "https://tusd.tusdemo.net/files/" })
      .use(GoogleDrive, { companionUrl: "https://companion.uppy.io" });

    this.uppy2 = new Uppy({ id: "uppy2", autoProceed: false, debug: true }).use(
      Tus,
      { endpoint: "https://tusd.tusdemo.net/files/" }
    );

    this.handleModalClick = this.handleModalClick.bind(this);
  }

  componentWillUnmount() {
    this.uppy.close({ reason: "unmount" });
    this.uppy2.close({ reason: "unmount" });
  }

  handleModalClick() {
    this.setState({
      open: !this.state.open,
    });
  }

  render() {
    const { showInlineDashboard } = this.state;
    return (
      <div>
        <h1>React Examples</h1>

        <h2>Inline Dashboard</h2>
        <label>
          <input
            type="checkbox"
            checked={showInlineDashboard}
            onChange={(event) => {
              this.setState({
                showInlineDashboard: event.target.checked,
              });
            }}
          />
          Show Dashboard
        </label>
        {showInlineDashboard && (
          <Dashboard
            uppy={this.uppy}
            plugins={["GoogleDrive"]}
            metaFields={[
              { id: "name", name: "Name", placeholder: "File name" },
            ]}
          />
        )}

        <h2>Modal Dashboard</h2>
        <div>
          <button onClick={this.handleModalClick}>
            {this.state.open ? "Close dashboard" : "Open dashboard"}
          </button>
          <DashboardModal
            uppy={this.uppy2}
            open={this.state.open}
            target={document.body}
            onRequestClose={() => this.setState({ open: false })}
          />
        </div>

        <h2>Drag Drop Area</h2>
        <DragDrop
          uppy={this.uppy}
          locale={{
            strings: {
              chooseFile: "Boop a file",
              orDragDrop: "or yoink it here",
            },
          }}
        />

        <h2>Progress Bar</h2>
        <ProgressBar uppy={this.uppy} hideAfterFinish={false} />

        <h2>File Input</h2>
        <FileInput uppy={this.uppy} />
      </div>
    );
  }
}
